version: '3.8'

services:
  roombarr:
    image: roombarr:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PUID: '${PUID}'
      PGID: '${PGID}'
      TZ: '${TZ}'
      RADARR_BASE_URL: '${RADARR_BASE_URL}'
      RADARR_PORT: '${RADARR_PORT}'
      RADARR_API_KEY: '${RADARR_API_KEY}'
      DISCORD_WEBHOOK_URL: '${DISCORD_WEBHOOK_URL}'
      LOG_LEVEL: '${LOG_LEVEL}'
      CRON_SCHEDULE: '${CRON_SCHEDULE}'
    volumes:
      - ./config:/config
